### ISSUE TITLE
Replying to users doesn't work

### ISSUE THREAD

**Issue by StormProductionsMusic** [bralbral/telegram-feedback-bot#40]
Hi,

So I just deployed the bot on my Ubuntu 22.04 VPS and I get the message from users, but when trying to reply from the account whose ID I have entered in the config file, it sends my reply as a new message and I receive it in the same conversation instead of actually replying to the user.

Am I doing something wrong, or does the bot nee an update?

Thanks!

**Comment by bralbral** [comment]
Hi, probably you confused by :

> Admin can answer to message by reply. The answer will be sent to the person who asked.

Let me explain how it works:

1. Somebody send message to bot. If message has avaiable content type

> Messages with an available content type (TEXT, ANIMATION, AUDIO, DOCUMENT, PHOTO, VIDEO, VOICE) will be transferred to admin group or admin chat.

it will transmitted to admin chat ( you can pass your account id in config file,) or admin group ( but without [topics](https://screenrant.com/telegram-create-topics-group-conversations-how/) ).

2. In admin chat/group you can interact with message of user by reply. But for user it will be seperate message. Reply exists only in admin chat/group.


I believe it is quite easy to add reply instead of separate message by collecting message_id from user.

This is a good idea, I would like to add it soon. But if you want, you can make a pull request.

**Comment by StormProductionsMusic** [comment]
I’m not a developer, please consider adding it then let me know after that’s done – I’m still looking for a bot to do that and havevn’t found any. Yours will be much appreciated if this is fixed! I need in private messages, not in groups. Since for me private message is easier. Thanks!  From: bralSent: Friday, April 19, 2024 9:43 PMTo: bralbral/telegram-feedback-botCc: StormProductionsMusic; AuthorSubject: Re: [bralbral/telegram-feedback-bot] Replying to users doesn't work (Issue #40) Hi, probably you confused by :Admin can answer to message by reply. The answer will be sent to the person who asked.Let me explain how it works:Somebody send message to bot. If message has avaiable content typeMessages with an available content type (TEXT, ANIMATION, AUDIO, DOCUMENT, PHOTO, VIDEO, VOICE) will be transferred to admin group or admin chat.it will transmitted to admin chat ( you can pass your account id in config file,) or admin group ( but without topics ).In admin chat/group you can interact with message of user by reply. But for user it will be seperate message. Reply exists only in admin chat/group.I believe it is quite easy to add reply instead of separate message by collecting message_id from user.This is a good idea, I would like to add it soon. But if you want, you can make a pull request.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by bralbral** [comment]
@StormProductionsMusic but it always seems to work with private message.

You should set your telegram_id of account in [this section](https://github.com/bralbral/telegram-feedback-bot/blob/main/deploy/example.config.yaml#L6) and then all messages from users will transmitted to private messages of this account.

But in that case you should start dialog before with bot from this account.

Just send /start from account which you added in config.yaml.

**Comment by StormProductionsMusic** [comment]
@bralbral, this seems pretty complicated to me. Can you please DM me on Telegram at https://t,me/stormproductions to get it sorted out? I'm pretty new to all this so would really need some help.

**Comment by StormProductionsMusic** [comment]
We're going to continue discussing this issue further on Telegram. Closing it now.
